name: nyetop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_svg_provider: ^1.0.7
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/onBoard1.png
    - assets/images/google_icon.png
    - assets/images/lock.svg
    - assets/images/profile.svg
    - assets/images/maki_arrow.svg

flutter_native_splash:
  color: "#060a56" 
  image: assets/images/wlogo.png 
  android_12:
    image: assets/images/wlogo.png
    color: "#060a56"
